[commands]
generate-token = """<green>Your new API key is <cyan>%token% <hover:show_text:"<gold>Click here to copy to your clipboard."><grey>(Click here to copy)"""
console-generate-token = "<grey>New server API key generated: '<gold>%token%<grey>'"
command-not-found = "<red>The command <gold>%subcommand% <red>does not exist!"
command-usage = "<grey>Correct usage: <gold>%usage%"
use-help-command = "<red>Use <gold>/api help <red>to see the list of existing commands"
invalid-arguments = "<red>The argument %argument% for this command is incorrect!"
not-enough-arguments = "<red>You need to enter more arguments to run this command!"
player-command-only = "<red>Only players can execute this command!"
no-permission = "<red>You don't have permission to execute this command!"
reload-successful = "<green>Plugin configuration files have been reloaded successfully."