[commands]
action-destructive = "<red>\nThis is a potentally destructive action!\nAre you sure you want to %action%? <grey>(y/n)"
action-warning = "<red>Are you sure you want to %action%<red>? <grey>(y/n)"
generate-token = "<green>Generated new API token <click:copy_to_clipboard:%token%><hover:show_text:'<aqua>%token%'><grey>(Click here to copy)</grey></hover></click>"
console-generate-token = "<grey>New server API key generated: '<gold>%token%<grey>'"
command-not-found = "<red>The command <gold>%subcommand% <red>does not exist!"
command-usage = "<grey>Correct usage: <gold>%usage%"
use-help-command = "<red>Use <gold>/api help <red>to see the list of existing commands"
invalid-arguments = "<red>The argument %argument% for this command is incorrect!"
not-enough-arguments = "<red>You need to enter more arguments to run this command!"
player-command-only = "<red>Only players can execute this command!"
no-permission = "<red>You don't have permission to execute this command!"
reload-successful = "<green>Plugin configuration files have been reloaded successfully."