name: Build plugin (multi version)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Update Permissions
        run: chmod +x ./gradlew
      - name: Create Multi Version Plugin
        run: ./gradlew multiVersionPlugin
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Move Builds
        run: ./gradlew -p project moveBuilds
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build
